baseURL = 'https://doda.co/'
languageCode = 'en-us'
title = 'Dominik Dabrowski'
theme = 'typo'

# Google analytics code
googleAnalytics = "G-xxxxxxxxx"

[taxonomies]
tag = 'tags'

[params]
# Meta description
description = "A Tech Blog"

# Appearance settings
theme = 'auto'
colorPalette = 'custom'
hideHeader = false

# Intro on main page, content is markdown
homeIntroTitle = 'Hi!'
homeIntroContent = """
I work on Systems at [Substack](https://substack.com). You can see some of the projects I've worked on in my [resume](). I am super excited about all things infrastructure engineering, machine learning and running things at scale.


I've been fortunate to live in 5 different countries and visit over 50, from early startup work in London and Berlin to settling in San Francisco.


In my free time I enjoy meditation, jhanas, CrossFit, painting and circling. I care deeply that what I do positively affects those around me. 


I'm usually at the Thursday sits at the [Berkeley Alembic](https://www.berkeleyalembic.org/).  If our paths cross in meaningful ways, don't hesitate to reach out!


"""

# Collection to display on home
homeCollectionTitle = 'Writing'
homeCollection = 'writing'

# Lists parameters
paginationSize = 100
listSummaries = true
listDateFormat = '2 Jan 2006'

# Breadcrumbs
[params.breadcrumbs]
enabled = true
showCurrentPage = true
home = "Home"

# Social icons
[[params.social]]
name = "linkedin"
url = "https://www.linkedin.com/in/dominik-dario/"

[[params.social]]
name = "github"
url = "https://github.com/doda"

# Main menu pages
[[params.menu]]
name = "home"
url = "/"

[[params.menu]]
name = "writing"
url = "/writing"

# Syntax highlight on code blocks
[markup]
[markup.highlight]
style = 'algol'

# Giscus comments
[params.giscus]
enable = false
repo = "user/repo"
repoid = "repoId"
category = "General"
categoryid = "categoryId"
mapping = "pathname"
theme = "preferred_color_scheme"

[caches]
  [caches.images]
    dir = ':cacheDir/images'
