baseURL = 'https://doda.co/'
languageCode = 'en-us'
title = 'Dominik Dabrowski'
theme = 'typo'

# Google analytics code
googleAnalytics = "G-xxxxxxxxx"

[taxonomies]
tag = 'tags'

[params]
# Meta description
description = "A Tech Blog"

# Appearance settings
theme = 'auto'
colorPalette = 'custom'
hideHeader = false
profilePicture = '/images/profile.jpg'

# Intro on main page, content is markdown
homeIntroTitle = 'Hi!'
homeIntroContent = """
I work on Systems at [Substack](https://substack.com). I am super excited about all things infra, AI and running things at scale.


I dropped out of school and moved to London to start working in startups at age 20, and then made my way to US via Berlin and Barcelona, where I've since settled in SF.


In my free time I enjoy meditation, jhanas, lifting and painting. I care deeply that what I do positively affects those around me. 


I'm usually at the Thursday sits at the [Berkeley Alembic](https://www.berkeleyalembic.org/).  If our paths cross in meaningful ways, don't hesitate to reach out!


"""

# Collection to display on home
homeCollectionTitle = 'Writing'
homeCollection = 'writing'

# Lists parameters
paginationSize = 100
listSummaries = true
listDateFormat = '2 Jan 2006'

# Breadcrumbs
[params.breadcrumbs]
enabled = true
showCurrentPage = true
home = "Home"

# Social icons
[[params.social]]
name = "linkedin"
url = "https://www.linkedin.com/in/dominik-dario/"

[[params.social]]
name = "github"
url = "https://github.com/doda"

[[params.social]]
name = "instagram"
url = "https://instagram.com/dominik_dario"

# Main menu pages
[[params.menu]]
name = "home"
url = "/"

[[params.menu]]
name = "writing"
url = "/writing"

# Syntax highlight on code blocks
[markup]
[markup.highlight]
style = 'algol'
[markup.goldmark]
[markup.goldmark.renderer]
unsafe = true

# Giscus comments
[params.giscus]
enable = false
repo = "user/repo"
repoid = "repoId"
category = "General"
categoryid = "categoryId"
mapping = "pathname"
theme = "preferred_color_scheme"

[caches]
  [caches.images]
    dir = ':cacheDir/images'
